(in-package #:cl-prolog-kit.tests)

(deftest-queries term-builtins ((make-rulebase))
  ((cl-prolog-kit::var ?x) :succeeds)
  ((and (= ?x value) (cl-prolog-kit::var ?x)) :fails)
  ((cl-prolog-kit::nonvar value) :succeeds)
  ((cl-prolog-kit::nonvar ?x) :fails)
  ((cl-prolog-kit::atom value) :succeeds)
  ((cl-prolog-kit::atom 3) :fails)
  ((cl-prolog-kit:atomic value) :succeeds)
  ((cl-prolog-kit:atomic 3/2) :fails)
  ((cl-prolog-kit:atomic ?x) :fails)
  ((cl-prolog-kit:atomic (node value)) :fails)
  ((cl-prolog-kit:atomic "value") :succeeds)
  ((cl-prolog-kit::number 3/2) :fails)
  ((cl-prolog-kit::number value) :fails)
  ((cl-prolog-kit::integer 3) :succeeds)
  ((cl-prolog-kit::integer 3/2) :fails)
  ((cl-prolog-kit:float 1.0) :succeeds)
  ((cl-prolog-kit:float 1) :fails)
  ((cl-prolog-kit:float ?x) :fails)
  ((and (= ?x 1.0d0) (cl-prolog-kit:float ?x)) :succeeds)
  ((cl-prolog-kit::== value value) :succeeds)
  ((cl-prolog-kit::== ?x ?x) :succeeds)
  ((cl-prolog-kit::== ?x ?y) :fails)
  ((and (cl-prolog-kit::|\\==| ?x ?y) (= ?x ?y)) :succeeds)
  ((cl-prolog-kit::|\\==| (node ?x) (node ?x)) :fails)
  ((cl-prolog-kit::|=@=| (pair ?x ?x) (pair ?y ?y)) :succeeds)
  ((cl-prolog-kit::|=@=| (pair ?x ?x) (pair ?y ?z)) :fails)
  ((cl-prolog-kit::|\\=@=| (pair ?x ?x) (pair ?y ?z)) :succeeds)
  ((and (cl-prolog-kit::|=@=| (pair ?x ?x) (pair ?y ?y))
        (cl-prolog-kit::var ?x)
        (cl-prolog-kit::var ?y))
   :succeeds)
  ((cl-prolog-kit::@< ?x atom) :succeeds)
  ((cl-prolog-kit::@< 2 atom) :succeeds)
  ((cl-prolog-kit::@< atom (node)) :succeeds)
  ((cl-prolog-kit::@< (a x) (b x)) :succeeds)
  ((cl-prolog-kit::@=< (node left) (node left)) :succeeds)
  ((cl-prolog-kit::@=< (node) atom) :fails)
  ((cl-prolog-kit::@> (node right) atom) :succeeds)
  ((cl-prolog-kit::@>= 2 2) :succeeds)
  ((cl-prolog-kit::@>= atom (node)) :fails)
  ((cl-prolog-kit::compare ?order 1 2) :ordered (((?order . <))))
  ;; ISO 13211-1 7.2.1: a Float precedes an Integer it compares equal to.
  ((cl-prolog-kit::compare ?order 1 1.0) :ordered (((?order . >))))
  ((cl-prolog-kit::compare ?order 1.0 1) :ordered (((?order . <))))
  ((cl-prolog-kit::compare ?order value value) :ordered (((?order . =))))
  ((cl-prolog-kit::compare ?order (node) value) :ordered (((?order . >))))
  ((cl-prolog-kit::compare ?order (a p) (a q)) :ordered (((?order . <))))
  ((and (cl-prolog-kit:unifiable (node ?x) (node value) ?unifier)
        (cl-prolog-kit::var ?x))
   :ordered (((?x . ?x) (?unifier (= ?x value)))))
  ((cl-prolog-kit:unifiable (pair ?y ?x) (pair left right) ?unifier)
   :ordered (((?y . ?y)
        (?x . ?x)
        (?unifier (= ?y left) (= ?x right)))))
  ((cl-prolog-kit:unifiable (pair ?x ?x) (pair value value) ?unifier)
   :ordered (((?x . ?x) (?unifier (= ?x value)))))
  ((cl-prolog-kit:unifiable (pair ?x ?x) (pair ?y value) ?unifier)
   :ordered (((?x . ?x)
        (?y . ?y)
        (?unifier (= ?x ?y) (= ?y value)))))
  ((cl-prolog-kit:unifiable (pair ?x ?x) (pair left right) ?unifier) :fails)
  ((cl-prolog-kit:unifiable ?x (node ?x) ?unifier) :fails)
  ((and (cl-prolog-kit::subsumes_term (node ?general) (node value))
        (cl-prolog-kit::var ?general))
   :succeeds)
  ((cl-prolog-kit::subsumes_term (pair ?x ?x) (pair same same)) :succeeds)
  ((cl-prolog-kit::subsumes_term (pair ?x ?x) (pair left right)) :fails)
  ((cl-prolog-kit::subsumes_term (node value) (node ?specific)) :fails)
  ((cl-prolog-kit::subsumes_term ?term (node ?specific)) :succeeds)
  ((cl-prolog-kit::term_variables (pair ?x (nested ?y ?x)) ?variables)
   :ordered (((?x . ?x) (?y . ?y) (?variables ?x ?y))))
  ((and (= ?x bound)
        (cl-prolog-kit::term_variables (pair ?x ?y) ?variables))
   :ordered (((?x . bound) (?y . ?y) (?variables ?y))))
  ((cl-prolog-kit::term_variables (pair ?x ?y ?x) ?variables (end))
   :ordered (((?x . ?x) (?y . ?y) (?variables ?x ?y end))))
  ((or (and (cl-prolog-kit::term_variables (pair ?x ?y) (?x))
            (= ?result leaked))
       (and (cl-prolog-kit::var ?x)
            (cl-prolog-kit::var ?y)
            (= ?result preserved)))
   :ordered (((?x . ?x) (?y . ?y) (?result . preserved))))
  ((cl-prolog-kit::compound (node left right)) :succeeds)
  ((cl-prolog-kit::compound value) :fails)
  ((cl-prolog-kit:callable value) :succeeds)
  ((cl-prolog-kit:callable nil) :succeeds)
  ((cl-prolog-kit:callable (node left right)) :succeeds)
  ((cl-prolog-kit:callable ?x) :fails)
  ((cl-prolog-kit:callable 3) :fails)
  ((cl-prolog-kit:callable "node") :fails)
  ((and (= ?goal (node left)) (cl-prolog-kit:callable ?goal)) :succeeds)
  ((cl-prolog-kit::ground (node left 3)) :succeeds)
  ((cl-prolog-kit::ground (node ?x 3)) :fails)
  ((cl-prolog-kit:acyclic_term (node ?x (leaf value))) :succeeds)
  ((cl-prolog-kit:cyclic_term (node ?x (leaf value))) :fails)
  ((cl-prolog-kit::functor (node left right) ?name ?arity)
   :ordered (((?name . node) (?arity . 2))))
  ((cl-prolog-kit::functor value ?name ?arity)
   :ordered (((?name . value) (?arity . 0))))
  ((cl-prolog-kit::functor ?term node 2) :succeeds)
  ((cl-prolog-kit::functor ?term 7 0) :ordered (((?term . 7))))
  ((cl-prolog-kit::arg 2 (node left right) ?value)
   :ordered (((?value . right))))
  ((cl-prolog-kit::arg 0 (node left right) ?value) :fails)
  ((cl-prolog-kit::arg 3 (node left right) ?value) :fails)
  ((and (cl-prolog-kit::copy_term (pair ?x ?x) ?copy)
        (= ?copy (pair copied copied)))
   :succeeds)
  ((and (cl-prolog-kit::copy_term (pair ?x ?x) ?copy)
        (= ?copy (pair left right)))
   :fails)
  ((or (and (cl-prolog-kit::copy_term (pair ?x ?x) ?copy)
            (= ?copy (pair left right)))
       (and (cl-prolog-kit::var ?x)
            (cl-prolog-kit::var ?copy)
            (= ?result preserved)))
   :ordered (((?x . ?x) (?copy . ?copy) (?result . preserved))))
  ;; numbervars/3 binds each variable to the ISO 8.14.2 functor `'$VAR''.  Its
  ;; text is upper case, so it has no bare symbol spelling; these specs are
  ;; quoted, so PROLOG-ATOM is called at read time.
  ((cl-prolog-kit:numbervars (pair ?x ?x ?y) 3 ?end)
   :ordered (((?x #.(cl-prolog-kit:prolog-atom "$VAR") 3)
        (?y #.(cl-prolog-kit:prolog-atom "$VAR") 4)
        (?end . 5))))
  ((and (= ?x bound)
        (cl-prolog-kit:numbervars (pair ?x ?y) 0 ?end))
   :ordered (((?x . bound) (?y #.(cl-prolog-kit:prolog-atom "$VAR") 0) (?end . 1))))
  ((or (and (cl-prolog-kit:numbervars (pair ?x ?y) 0 1)
            (= ?result leaked))
       (and (cl-prolog-kit::var ?x)
            (cl-prolog-kit::var ?y)
            (= ?result preserved)))
   :ordered (((?x . ?x) (?y . ?y) (?result . preserved))))
  ((cl-prolog-kit::|=..| (node left right) ?list)
   :ordered (((?list node left right))))
  ((cl-prolog-kit::|=..| value ?list)
   :ordered (((?list value))))
  ((cl-prolog-kit::|=..| ?term (node left right))
   :ordered (((?term node left right))))
  ((cl-prolog-kit::|=..| ?term (value))
   :ordered (((?term . value)))))

(deftest cyclic-term-detection-handles-circular-and-shared-conses ()
  (let* ((shared (list 'leaf 'value))
         (acyclic (list 'pair shared shared))
         (car-cycle (list 'node))
         (cdr-cycle (list 'node)))
    (setf (car car-cycle) car-cycle
          (cdr cdr-cycle) cdr-cycle)
    (is (cl-prolog-kit::%term-acyclic-p acyclic))
    (is (not (cl-prolog-kit::%term-acyclic-p car-cycle)))
    (is (not (cl-prolog-kit::%term-acyclic-p cdr-cycle)))
    (is (not (cl-prolog-kit::%term-acyclic-p
              '?cycle '((?cycle node ?cycle)))))))

(deftest public-cyclic-term-builtins-detect-cdr-cycles ()
  (let ((cycle (list (quote node))))
    (setf (cdr cycle) cycle)
    (let ((rulebase (make-rulebase)))
      (is-equal 1
                (length (query-prolog rulebase
                                      (list (quote cl-prolog-kit:cyclic_term) cycle))))
      (is (null (query-prolog rulebase
                             (list (quote cl-prolog-kit:acyclic_term) cycle)))))))

(defun term-builtin-error-summary (goal)
  (query-error-summary (make-rulebase) goal :with-data t))

(deftest-table term-builtins-report-iso-errors ()
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (term-builtin-error-summary '(cl-prolog-kit::functor ?term ?name 1)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (term-builtin-error-summary '(cl-prolog-kit::functor ?term node ?arity)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "ATOMIC" ("BAD" "NAME")))
          (term-builtin-error-summary '(cl-prolog-kit::functor ?term (bad name) 1)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "INTEGER" 1.0))
          (term-builtin-error-summary '(cl-prolog-kit::functor ?term node 1.0)))
  (:equal '(prolog-domain-error ("DOMAIN_ERROR" "NOT_LESS_THAN_ZERO" -1))
          (term-builtin-error-summary '(cl-prolog-kit::functor ?term node -1)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "ATOM" 7))
          (term-builtin-error-summary '(cl-prolog-kit::functor ?term 7 1)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (term-builtin-error-summary '(cl-prolog-kit::arg ?index (node value) ?value)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "INTEGER" 1.0))
          (term-builtin-error-summary '(cl-prolog-kit::arg 1.0 (node value) ?value)))
  (:equal '(prolog-domain-error ("DOMAIN_ERROR" "NOT_LESS_THAN_ZERO" -1))
          (term-builtin-error-summary '(cl-prolog-kit::arg -1 (node value) ?value)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (term-builtin-error-summary '(cl-prolog-kit::arg 1 ?term ?value)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "COMPOUND" "ATOM"))
          (term-builtin-error-summary '(cl-prolog-kit::arg 1 atom ?value)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (term-builtin-error-summary '(cl-prolog-kit:numbervars (pair ?x) ?start ?end)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "INTEGER" 1.0))
          (term-builtin-error-summary '(cl-prolog-kit:numbervars (pair ?x) 1.0 ?end)))
  (:equal '(prolog-domain-error ("DOMAIN_ERROR" "NOT_LESS_THAN_ZERO" -1))
          (term-builtin-error-summary '(cl-prolog-kit:numbervars (pair ?x) -1 ?end)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (term-builtin-error-summary '(cl-prolog-kit::|=..| ?term ?list)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "LIST" "IMPROPER"))
          (term-builtin-error-summary '(cl-prolog-kit::|=..| ?term improper)))
  (:equal '(prolog-domain-error ("DOMAIN_ERROR" "NON_EMPTY_LIST" nil))
          (term-builtin-error-summary '(cl-prolog-kit::|=..| ?term nil)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (term-builtin-error-summary '(cl-prolog-kit::|=..| ?term (?head value))))
  (:equal '(prolog-type-error ("TYPE_ERROR" "ATOM" 7))
          (term-builtin-error-summary '(cl-prolog-kit::|=..| ?term (7 value))))
  ;; A ratio is a host value that is no Prolog term at all (see
  ;; HOST-ONLY-NUMBERS-ARE-NOT-PROLOG-NUMBERS), so it is neither decomposable
  ;; nor usable as a one-element list's atomic term.  Only the Lisp API can
  ;; present one; Prolog source has no syntax for it.
  (:equal '(prolog-type-error ("TYPE_ERROR" "CALLABLE" 3/2))
          (term-builtin-error-summary '(cl-prolog-kit::functor 3/2 ?name ?arity)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "CALLABLE" 3/2))
          (term-builtin-error-summary '(cl-prolog-kit::|=..| 3/2 ?list)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "ATOMIC" 3/2))
          (term-builtin-error-summary '(cl-prolog-kit::|=..| ?term (3/2)))))

(deftest atom-order-ranks-a-prefix-before-its-extension ()
  "ISO 13211-1 7.2.3 compares atoms character by character and then by length,
so an atom that is a proper prefix of another precedes it in both directions."
  (is (= -1 (cl-prolog-kit::%compare-terms (quote cl-prolog-kit::ab) (quote cl-prolog-kit::abc))))
  (is (= 1 (cl-prolog-kit::%compare-terms (quote cl-prolog-kit::abc) (quote cl-prolog-kit::ab))))
  (is (= -1 (cl-prolog-kit::%compare-atom-texts (quote cl-prolog-kit::ab) (quote cl-prolog-kit::abc))))
  (is (= 1 (cl-prolog-kit::%compare-atom-texts (quote cl-prolog-kit::abc) (quote cl-prolog-kit::ab))))
  (is (= 0 (cl-prolog-kit::%compare-atom-texts (quote cl-prolog-kit::abc)
                                           (prolog-atom "abc")))))

(deftest term-order-properties ()
  (cl-prolog-kit::%with-logic-variable-order
    (let ((terms (list (cl-prolog-kit:fresh-logic-variable "?Z")
                       -3 1 1.0 3/2 'alpha 'beta '(node) '(node left))))
      (dolist (left terms)
        (dolist (right terms)
          (let ((forward (cl-prolog-kit::%compare-terms left right))
                (reverse (cl-prolog-kit::%compare-terms right left)))
            (is (= forward (- reverse)))
            (is (member forward '(-1 0 1)))))))))

(deftest host-only-numbers-are-not-prolog-numbers ()
  (dolist (number (list 3/2 (complex 1 2)))
    (is (not (cl-prolog-kit::%prolog-number-p number)))
    (is (= 5 (cl-prolog-kit::%term-order-class number))))
  (dolist (number (list 1 1.0))
    (is (cl-prolog-kit::%prolog-number-p number))
    (is (= 1 (cl-prolog-kit::%term-order-class number))))
  (let ((rulebase (make-rulebase))
        (number (complex 1 2)))
    (is (null (query-prolog rulebase (list (quote cl-prolog-kit:atomic) number))))
    (is (null (query-prolog rulebase (list (quote cl-prolog-kit::number) number))))))

(deftest cyclic-term-identity-variants-and-order ()
  (let ((left (cons 'node nil))
        (right (cons 'node nil))
        (different (cons 'other nil)))
    (setf (cdr left) left
          (cdr right) right
          (cdr different) different)
    (is (cl-prolog-kit::%term-identical-p left right))
    (is (not (cl-prolog-kit::%term-identical-p left different)))
    (is (cl-prolog-kit::%term-variant-p left right))
    (let ((forward (cl-prolog-kit::%compare-terms left different))
          (reverse (cl-prolog-kit::%compare-terms different left)))
      (is (member forward '(-1 1)))
      (is (= forward (- reverse))))))

(deftest term-variant-rejects-mismatched-shapes ()
  (is (not (cl-prolog-kit::%term-variant-p 'cl-prolog-kit::foo '?x)))
  (is (not (cl-prolog-kit::%term-variant-p '(cl-prolog-kit::foo cl-prolog-kit::a) 'cl-prolog-kit::bar))))

(deftest term-order-identifies-equal-text-atoms-across-packages ()
  "An atom is its text, so two symbols spelling the same atom are one atom
however they were interned -- the parser puts a name inherited from COMMON-LISP
in USER-ATOMS while the Lisp reader leaves it in COMMON-LISP.  The standard
order must therefore agree with unification instead of ranking them by package,
or `X = Y' and `X @< Y' could both hold."
  (let* ((name "PACKAGE-SENSITIVE-ATOM")
         (left (intern name (find-package '#:cl-prolog-kit)))
         (right (intern name (find-package '#:cl-prolog-kit.tests))))
    (is (not (eq left right)))
    (is (= 0 (cl-prolog-kit::%compare-terms left right)))
    (is (= 0 (cl-prolog-kit::%compare-terms right left)))
    (is (cl-prolog-kit::%term-identical-p left right))
    (is (nth-value 1 (unify left right)))))

(deftest term-order-identifies-uninterned-equal-text-atoms ()
  (let ((left (make-symbol "SAME-NAME-ATOM"))
        (right (make-symbol "SAME-NAME-ATOM")))
    (is (not (eq left right)))
    (is (= 0 (cl-prolog-kit::%compare-terms left right)))
    (is (= 0 (cl-prolog-kit::%compare-terms right left)))))

(deftest term-order-ranks-atoms-by-character-code-of-their-text ()
  "ISO 13211-1 7.2.3 orders atoms by their characters, so the upper-case `'B''
precedes the lower-case `a' -- the reverse of the order their internal symbol
names would give."
  (let ((upper (prolog-atom "B"))
        (lower 'cl-prolog-kit::a))
    (is (= -1 (cl-prolog-kit::%compare-terms upper lower)))
    (is (= 1 (cl-prolog-kit::%compare-terms lower upper)))
    (is (not (= 0 (cl-prolog-kit::%compare-terms (prolog-atom "ABC")
                                             'cl-prolog-kit::abc))))))

(deftest term-order-compares-improper-terms-by-their-tails ()
  "An improper term is compared element-wise like any other cons, so a pair
whose cars are one atom is decided by its cdrs."
  (let ((left (cons (quote cl-prolog-kit::a) (quote cl-prolog-kit::b)))
        (right (cons (quote cl-prolog-kit::a) (quote cl-prolog-kit::c))))
    (is (= -1 (cl-prolog-kit::%compare-terms left right)))
    (is (= 1 (cl-prolog-kit::%compare-terms right left)))))

(deftest term-order-ranks-strings-in-both-directions ()
  (is (= -1 (cl-prolog-kit::%compare-terms "a" "b")))
  (is (= 1 (cl-prolog-kit::%compare-terms "b" "a")))
  (is (= 0 (cl-prolog-kit::%compare-terms "a" (copy-seq "a")))))

(deftest term-order-separates-numerically-equal-floats-of-different-types ()
  "1.0f0 and 1.0d0 are = but not EQL, so neither the value comparison nor the
float/integer rule can separate them; the standard order still has to be a
total order, so they fall back to their printed text -- antisymmetric and
never 0, whatever *READ-DEFAULT-FLOAT-FORMAT* makes that text."
  (let ((forward (cl-prolog-kit::%compare-terms 1.0f0 1.0d0))
        (reverse (cl-prolog-kit::%compare-terms 1.0d0 1.0f0)))
    (is (member forward (quote (-1 1))))
    (is (= forward (- reverse)))))

(deftest term-order-rejects-two-host-only-terms ()
  "A ratio is not a Prolog term (see HOST-ONLY-NUMBERS-ARE-NOT-PROLOG-NUMBERS);
two of them share an order class no ordering rule covers, so comparing them is
an error rather than a silent arbitrary answer."
  (signals-error (cl-prolog-kit::%compare-terms 3/2 1/2))
  (signals-error (cl-prolog-kit::%compare-terms (complex 1 2) (complex 3 4))))

(deftest term-variant-rejects-a-variable-against-a-non-variable ()
  "The mirror of TERM-VARIANT-REJECTS-MISMATCHED-SHAPES: a variable on the
left is no more a variant of a non-variable than one on the right."
  (is (not (cl-prolog-kit::%term-variant-p (quote ?x) (quote cl-prolog-kit::foo))))
  (is (not (cl-prolog-kit::%term-variant-p (quote (cl-prolog-kit::pair ?x))
                                       (quote (cl-prolog-kit::pair cl-prolog-kit::foo))))))

(deftest term-order-uses-variable-creation-order ()
  (cl-prolog-kit::%with-logic-variable-order
    (let ((first (cl-prolog-kit:fresh-logic-variable "?Z"))
          (second (cl-prolog-kit:fresh-logic-variable "?A")))
      (is (= -1 (cl-prolog-kit::%compare-terms first second)))
      (is (= 1 (cl-prolog-kit::%compare-terms second first))))))

(cl-weave:it-property
    "copy_term/2 always produces a variant of its input"
    ((term (let ((variables (list (cl-prolog-kit:fresh-logic-variable "?A")
                                  (cl-prolog-kit:fresh-logic-variable "?B"))))
             (cl-weave:gen-recursive
              (cl-weave:gen-one-of
               (cl-weave:gen-integer :min -100 :max 100)
               (cl-weave:gen-member '(cl-prolog-kit::foo cl-prolog-kit::bar))
               (cl-weave:gen-member variables))
              (lambda (self)
                (cl-weave:gen-list self :min-length 1 :max-length 3))
              :max-depth 3))))
  (cl-weave:expect-has-assertions)
  (cl-prolog-kit::%with-logic-variable-order
    (multiple-value-bind (solution succeeded-p)
        (query-prolog-first (make-rulebase)
                            (list 'cl-prolog-kit::copy_term term '?copy))
      (is succeeded-p)
      (is (cl-prolog-kit::%term-variant-p
           term (solution-binding '?copy solution))))))
