;;;; char_type/2, code_type/2, upcase_atom/2, downcase_atom/2 tests.
;;;;
;;;; A bare symbol is the lower-case atom it reads as, so `a' is the character
;;;; atom `a'.  An atom whose text holds an upper-case letter has no bare
;;;; spelling and is written #.(cl-prolog-kit:prolog-atom "A"), which these quoted
;;;; specs evaluate at read time.

(in-package #:cl-prolog-kit.tests)

(deftest-queries char-type-builtin ((make-rulebase))
  ((cl-prolog-kit::char_type a alpha)      :succeeds)
  ((cl-prolog-kit::char_type |5| alpha)      :fails)
  ((cl-prolog-kit::char_type a alnum)      :succeeds)
  ((cl-prolog-kit::char_type |5| digit)      :succeeds)
  ((cl-prolog-kit::char_type #.(cl-prolog-kit:prolog-atom "A") upper)      :succeeds)
  ((cl-prolog-kit::char_type a lower)      :succeeds)
  ((cl-prolog-kit::char_type |_| csym)       :succeeds)
  ((cl-prolog-kit::char_type |_| csymf)      :succeeds)
  ((cl-prolog-kit::char_type |9| csymf)      :fails)
  ((cl-prolog-kit::char_type |.| punct)      :succeeds)
  ((cl-prolog-kit::char_type | | space)      :succeeds)
  ((cl-prolog-kit::char_type a space)      :fails)
  ((cl-prolog-kit::char_type a graph)      :succeeds)
  ((cl-prolog-kit::char_type | | graph)      :fails)
  ((cl-prolog-kit::char_type a ascii)      :succeeds)
  ((cl-prolog-kit::char_type |.| period)     :succeeds)
  ((cl-prolog-kit::char_type |+| graphic)    :succeeds)
  ((cl-prolog-kit::char_type a graphic)    :fails)
  ((cl-prolog-kit::char_type |7| (digit ?w)) :ordered (((?w . 7))))
  ((cl-prolog-kit::char_type a (to_upper ?u)) :ordered (((?u . #.(cl-prolog-kit:prolog-atom "A")))))
  ((cl-prolog-kit::char_type #.(cl-prolog-kit:prolog-atom "A") (to_lower ?l)) :ordered (((?l . cl-prolog-kit::a))))
  ((cl-prolog-kit::char_type #.(cl-prolog-kit:prolog-atom "A") (upper ?l)) :ordered (((?l . cl-prolog-kit::a))))
  ((cl-prolog-kit::char_type a (lower ?u)) :ordered (((?u . #.(cl-prolog-kit:prolog-atom "A")))))
  ((cl-prolog-kit::char_type a (code ?c))  :ordered (((?c . 97))))
  ((cl-prolog-kit::char_type a (upper ?l)) :fails)
  ((cl-prolog-kit::char_type ?v alpha)       :signals)
  ((cl-prolog-kit::char_type ab alpha)       :signals)
  ((cl-prolog-kit::char_type a bogus)      :signals)
  ;; a type argument that is a variable, a non-atom, or an improper list
  ;; must raise a catchable error rather than crash the host.
  ((cl-prolog-kit::char_type a ?type)      :signals)
  ((cl-prolog-kit::char_type a 42)         :signals)
  ((cl-prolog-kit::char_type a (|.| . x))  :signals)
  ((cl-prolog-kit::char_type a (bogus ?x)) :signals))

(deftest-queries code-type-builtin ((make-rulebase))
  ((cl-prolog-kit::code_type 97 alpha)        :succeeds)
  ((cl-prolog-kit::code_type 53 digit)        :succeeds)
  ((cl-prolog-kit::code_type 65 upper)        :succeeds)
  ((cl-prolog-kit::code_type 97 (to_upper ?u)) :ordered (((?u . 65))))
  ((cl-prolog-kit::code_type 65 (to_lower ?l)) :ordered (((?l . 97))))
  ((cl-prolog-kit::code_type 97 (code ?c))    :ordered (((?c . 97))))
  ((cl-prolog-kit::code_type 55 (digit ?w))   :ordered (((?w . 7))))
  ((cl-prolog-kit::code_type ?v alpha)        :signals)
  ((cl-prolog-kit::code_type -1 alpha)        :signals)
  ((cl-prolog-kit::code_type 9999999999 alpha) :signals)
  ((cl-prolog-kit::code_type 1.5d0 alpha)     :signals))

(deftest-queries case-fold-builtins ((make-rulebase))
  ((cl-prolog-kit::upcase_atom hello ?u)     :ordered (((?u . #.(cl-prolog-kit:prolog-atom "HELLO")))))
  ((cl-prolog-kit::downcase_atom #.(cl-prolog-kit:prolog-atom "HeLLo") ?d) :ordered (((?d . cl-prolog-kit::hello))))
  ((cl-prolog-kit::upcase_atom #.(cl-prolog-kit:prolog-atom "MiXeD") ?u)   :ordered (((?u . #.(cl-prolog-kit:prolog-atom "MIXED")))))
  ((cl-prolog-kit::upcase_atom 42 ?u)        :ordered (((?u . cl-prolog-kit::|42|))))
  ((cl-prolog-kit::upcase_atom ?v ?u)        :signals)
  ((cl-prolog-kit::upcase_atom (foo bar) ?u) :signals))
