;;;; List builtin tests: member/2, memberchk/2, select/3, and other
;;;; list-processing predicates, plus cyclic-list/cyclic-term handling.

(in-package #:cl-prolog-kit.tests)

(deftest-queries list-builtins ((make-rulebase))
  ((member ?x (bob alice))       :set (((?x . bob)) ((?x . alice))))
  ((member bob (bob alice))      :ordered (nil))
  ((and (member ?x (a b . ?tail)) (= ?tail end))
                                   :ordered (((?x . a) (?tail . end))
                                       ((?x . b) (?tail . end))) :limit 2)
  ((and (member wanted ?unbound) (= ?unbound (wanted tail)))
                                   :ordered (((?unbound wanted tail))) :limit 1)
  ((cl-prolog-kit::memberchk ?x (a b a)) :ordered (((?x . a))))
  ((cl-prolog-kit::memberchk z (a b)) :fails)
  ((cl-prolog-kit::memberchk wanted ?xs) :succeeds)
  ((cl-prolog-kit::select ?x (a b a) ?rest)
                                   :ordered (((?x . a) (?rest b a))
                                       ((?x . b) (?rest a a))
                                       ((?x . a) (?rest a b))))
  ((cl-prolog-kit::select b ?list (a c))
                                   :ordered (((?list . (b a c)))
                                       ((?list . (a b c)))
                                       ((?list . (a c b)))) :limit 3)
  ((and (cl-prolog-kit::select b (a b . ?tail) ?rest)
        (= ?tail (c)))           :ordered (((?tail . (c)) (?rest a c))) :limit 1)
  ((cl-prolog-kit::select z (a b . improper) ?rest) :fails)
  ((cl-prolog-kit::nth0 1 (a b c) ?x) :ordered (((?x . b))))
  ((cl-prolog-kit::nth0 ?n (a b c) ?x)
                                   :ordered (((?n . 0) (?x . a))
                                       ((?n . 1) (?x . b))
                                       ((?n . 2) (?x . c))))
  ((cl-prolog-kit::nth1 ?n (a b c) b) :ordered (((?n . 2))))
  ((and (cl-prolog-kit::nth0 2 (a . ?tail) c)
        (= ?tail (b c d)))       :ordered (((?tail b c d))))
  ((cl-prolog-kit::nth0 3 (a b . improper) ?x) :fails)
  ((cl-prolog-kit::nth0 -1 (a b) ?x) :signals)
  ((cl-prolog-kit::nth0 not-an-integer (a b) ?x) :signals)
  ((cl-prolog-kit::nth1 0 (a b) ?x) :signals)
  ((cl-prolog-kit::last (a b c) ?x) :ordered (((?x . c))))
  ((cl-prolog-kit::last (singleton) singleton) :succeeds)
  ((cl-prolog-kit::last (a b . improper) ?x) :fails)
  ((and (cl-prolog-kit::last (a b . ?tail) c) (= ?tail (c)))
                                   :ordered (((?tail . (c)))) :limit 1)
  ((cl-prolog-kit::is_list ())       :succeeds)
  ((cl-prolog-kit::is_list (a b c))  :succeeds)
  ((cl-prolog-kit::is_list (a b . improper)) :fails)
  ((cl-prolog-kit::is_list ?unbound) :fails)
  ((append (a b) (c) ?xs)        :ordered (((?xs . (a b c)))))
  ((append (a b) ?tail (a b c))  :ordered (((?tail . (c)))))
  ((append ?left ?right (a b c)) :ordered (((?left . ()) (?right . (a b c)))
                                     ((?left . (a)) (?right . (b c)))
                                     ((?left . (a b)) (?right . (c)))
                                     ((?left . (a b c)) (?right . ()))))
  ((append (a . ?tail) (c) (a b c))
                                   :ordered (((?tail . (b)))))
  ((and (append ?left ?right ?any) (= ?any (a b)))
                                   :ordered (((?left . ()) (?right . (a b)) (?any a b))
                                       ((?left . (a)) (?right . (b)) (?any a b))
                                       ((?left . (a b)) (?right . ()) (?any a b))) :limit 3)
  ((reverse (a b c) ?x)          :ordered (((?x . (c b a)))))
  ((reverse ?x (c b a))          :ordered (((?x . (a b c)))))
  ((reverse (a . ?tail) (c b a)) :ordered (((?tail . (b c)))))
  ((reverse atom other)          :fails)
  ((length (a b c) ?n)           :ordered (((?n . 3))))
  ((length ?xs 0)                :ordered (((?xs))))
  ((length ?xs 2)                :succeeds)
  ((and (length ?xs ?n) (= ?n 2)):succeeds)
  ((length (a b . ?tail) 4)      :succeeds)
  ((length ?xs -1)               :signals)
  ((length ?xs not-a-number)     :signals))

(in-package #:cl-prolog-kit.tests)

(deftest cyclic-list-builtins-terminate ()
  (let* ((self-cycle (list 'a))
         (two-node-cycle (list 'a 'b))
         (shared-tail (list 'b 'c))
         (shared-list (cons 'a shared-tail))
         (rulebase (make-rulebase)))
    (setf (cdr self-cycle) self-cycle
          (cddr two-node-cycle) two-node-cycle)
    (labels ((solutions (predicate &rest arguments)
               (let ((environments '()))
                 (funcall (cl-prolog-kit::%goal-solver predicate (length arguments))
                          (cons predicate arguments) rulebase nil nil
                          (lambda (environment)
                            (push environment environments)))
                 (nreverse environments)))
             (fails-without-looping (predicate &rest arguments)
               (is (null (apply #'solutions predicate arguments))))
             (check-cycle (cycle)
               (fails-without-looping 'cl-prolog-kit::is_list cycle)
               (fails-without-looping 'cl-prolog-kit::member 'missing cycle)
               (fails-without-looping 'cl-prolog-kit::memberchk 'missing cycle)
               (fails-without-looping
                'cl-prolog-kit::select 'missing cycle
                (cl-prolog-kit:fresh-logic-variable "?REST"))
               (fails-without-looping
                'cl-prolog-kit::nth0 8 cycle
                (cl-prolog-kit:fresh-logic-variable "?ITEM"))
               (fails-without-looping
                'cl-prolog-kit::nth1 8 cycle
                (cl-prolog-kit:fresh-logic-variable "?ITEM"))
               (fails-without-looping
                'cl-prolog-kit::last cycle
                (cl-prolog-kit:fresh-logic-variable "?ITEM"))
               (fails-without-looping
                'cl-prolog-kit::append cycle nil
                (cl-prolog-kit:fresh-logic-variable "?RESULT"))
               (fails-without-looping
                'cl-prolog-kit::reverse cycle
                (cl-prolog-kit:fresh-logic-variable "?REVERSED"))
               (fails-without-looping
                'cl-prolog-kit::length cycle
                (cl-prolog-kit:fresh-logic-variable "?LENGTH"))))
      (let ((item (cl-prolog-kit:fresh-logic-variable "?ITEM")))
        (is-equal '(a a b)
                  (mapcar (lambda (environment)
                            (cl-prolog-kit:logic-substitute item environment))
                          (solutions 'cl-prolog-kit::member item '(a a b)))))
      (is-equal 1 (length (solutions 'cl-prolog-kit::member 'a self-cycle)))
      (is-equal 1 (length (solutions 'cl-prolog-kit::member 'a two-node-cycle)))
      (is-equal 1 (length (solutions 'cl-prolog-kit::member 'b two-node-cycle)))
      (check-cycle self-cycle)
      (check-cycle two-node-cycle)
      (is-equal 1 (length (solutions 'cl-prolog-kit::member 'c shared-list)))
      (is-equal 1 (length (solutions 'cl-prolog-kit::memberchk 'c shared-list)))
      (is-equal 1 (length (solutions 'cl-prolog-kit::select 'a shared-list shared-tail)))
      (is-equal 1 (length (solutions 'cl-prolog-kit::nth0 2 shared-list 'c)))
      (is-equal 1 (length (solutions 'cl-prolog-kit::nth1 3 shared-list 'c)))
      (is-equal 1 (length (solutions 'cl-prolog-kit::last shared-list 'c)))
      (is-equal 1 (length (solutions 'cl-prolog-kit::is_list shared-list)))
      (is-equal 1 (length (solutions 'cl-prolog-kit::append shared-list nil shared-list)))
      (is-equal 1 (length (solutions 'cl-prolog-kit::reverse shared-list '(c b a))))
      (is-equal 1 (length (solutions 'cl-prolog-kit::length shared-list 3))))))

(deftest cyclic-copy-helpers-preserve-cycles-and-sharing ()
  (cl-prolog-kit::%with-logic-variable-order
    (let* ((variable (cl-prolog-kit:fresh-logic-variable "?SOURCE"))
           (cycle (cons variable nil))
           (shared (list (quote shared)))
           (root (cons shared shared)))
      (setf (cdr cycle) cycle)
      (let ((freshened (cl-prolog-kit::%freshen-term
                        cycle (make-hash-table :test (function eq)))))
        (is (not (eq freshened cycle)))
        (is (eq freshened (cdr freshened)))
        (is (cl-prolog-kit:logic-var-p (car freshened)))
        (is (not (eq variable (car freshened)))))
      (let ((freshened (cl-prolog-kit::%freshen-term
                        root (make-hash-table :test (function eq)))))
        (is (eq (car freshened) (cdr freshened))))
      (let ((canonical (cl-prolog-kit::%canonicalize-variant cycle)))
        (is (eq canonical (cdr canonical))))
      (let ((canonical (cl-prolog-kit::%canonicalize-variant root)))
        (is (eq (car canonical) (cdr canonical))))
      (let* ((alias (cl-prolog-kit:fresh-logic-variable "?ALIAS"))
             (alias-target (cl-prolog-kit:fresh-logic-variable "?ALIAS-TARGET"))
             (residual (cl-prolog-kit:fresh-logic-variable "?RESIDUAL"))
             (shared (cons residual (quote shared-tail)))
             (cycle (cons alias nil))
             (root (list alias shared cycle residual))
             (index (cl-prolog-kit::%make-environment-index
                     (list (cons alias alias-target)
                           (cons alias-target shared)))))
        (setf (cdr cycle) cycle)
        (multiple-value-bind (legacy legacy-cyclic-p legacy-variables-p)
            (cl-prolog-kit::%canonicalize-variant
             (cl-prolog-kit::%logic-substitute-indexed root index))
          (multiple-value-bind (fused fused-cyclic-p fused-variables-p)
              (cl-prolog-kit::%canonicalize-variant root index)
            (is-equal (cl-prolog-kit::%variant-graph-key legacy)
                      (cl-prolog-kit::%variant-graph-key fused))
            (is (eql legacy-cyclic-p fused-cyclic-p))
            (is (eql legacy-variables-p fused-variables-p))
            (is (not (eq fused root)))
            (is (not (eq (first fused) shared)))
            (is (eq (first fused) (second fused)))
            (is (eq (first fused) (car (third fused))))
            (is (eq (third fused) (cdr (third fused))))
            (is (eq (car (first fused)) (fourth fused)))))))))
(deftest variant-canonicalization-preserves-graph-across-copy-map-promotion ()
  (let* ((capacity 16)
         (shared (list 'shared))
         (spine (make-list (1- capacity)))
         (root (cons shared spine))
         (last-spine (nthcdr (- capacity 2) spine)))
    (setf (car last-spine) shared
          (cdr last-spine) root)
    (multiple-value-bind (canonical cyclic-p contains-variables-p)
        (cl-prolog-kit::%canonicalize-variant root)
      (is (not contains-variables-p))
      (let ((canonical-last
              (nthcdr (- capacity 2) (cdr canonical))))
        (is (not (eq canonical root)))
        (is cyclic-p)
        (is (eq canonical (cdr canonical-last)))
        (is (eq (car canonical)
                (car canonical-last)))))))
(defun variant-canonicalization-full-cycle-summary (length)
  "Canonicalize a LENGTH-element list whose tail points back at its own head."
  (let* ((root (make-list length))
         (last (last root)))
    (setf (cdr last) root)
    (multiple-value-bind (canonical cyclic-p contains-variables-p)
        (cl-prolog-kit::%canonicalize-variant root)
      (list :contains-variables contains-variables-p
            :fresh-copy (not (eq canonical root))
            :cyclic cyclic-p
            :back-edge-at-root (eq canonical (nthcdr length canonical))))))

(deftest-table variant-canonicalization-full-cycle-backedges-preserve-the-copy-root ()
  (:equal '(:contains-variables nil :fresh-copy t :cyclic t :back-edge-at-root t)
          (variant-canonicalization-full-cycle-summary 4)
          "A four-cons backedge preserves the copy root")
  (:equal '(:contains-variables nil :fresh-copy t :cyclic t :back-edge-at-root t)
          (variant-canonicalization-full-cycle-summary 5)
          "A five-cons promotion backedge preserves the copy root"))
(deftest variant-canonicalization-post-promotion-shared-dag-stays-acyclic ()
  (let* ((variable (cl-prolog-kit:fresh-logic-variable "?SHARED"))
         (shared (list variable))
         (root (list shared 'a 'b 'c 'd shared)))
    (multiple-value-bind (canonical cyclic-p contains-variables-p)
        (cl-prolog-kit::%canonicalize-variant root)
      (is contains-variables-p)
      (is (not (eq canonical root)))
      (is (not cyclic-p))
      (is (eq (first canonical) (sixth canonical))))))


(deftest variant-instantiation-restores-shared-table-variables ()
  (cl-prolog-kit::%with-logic-variable-order
    (let* ((variable (cl-prolog-kit:fresh-logic-variable "?SOURCE"))
           (canonical (cl-prolog-kit::%canonicalize-variant (list variable variable)))
           (instantiated (cl-prolog-kit::%instantiate-variant canonical)))
      (is (cl-prolog-kit:logic-var-p (first instantiated)))
      (is (eq (first instantiated) (second instantiated)))
      (is (not (eq variable (first instantiated)))))))

(deftest variant-instantiation-copies-a-malformed-marker-shaped-node ()
  (let ((malformed (list cl-prolog-kit::+variant-variable-marker+ 0 'extra)))
    (is-equal malformed (cl-prolog-kit::%instantiate-variant malformed))))

(cl-weave:it-property
    "canonicalizing an instantiated variant reproduces the same canonical form"
    ((term (let ((variables (list (cl-prolog-kit:fresh-logic-variable "?A")
                                  (cl-prolog-kit:fresh-logic-variable "?B")
                                  (cl-prolog-kit:fresh-logic-variable "?C"))))
             (cl-weave:gen-recursive
              (cl-weave:gen-one-of (cl-weave:gen-integer :min -10 :max 10)
                                   (cl-weave:gen-member '(a b c))
                                   (cl-weave:gen-member variables))
              (lambda (self) (cl-weave:gen-list self :min-length 0 :max-length 3))
              :max-depth 3))))
  (cl-weave:expect-has-assertions)
  (cl-prolog-kit::%with-logic-variable-order
    (let* ((canonical (cl-prolog-kit::%canonicalize-variant term))
           (instantiated (cl-prolog-kit::%instantiate-variant canonical))
           (recanonical (cl-prolog-kit::%canonicalize-variant instantiated)))
      (cl-weave:expect recanonical :to-equal canonical))))

(deftest findall-with-cyclic-tail-terminates ()
  (cl-prolog-kit::%with-logic-variable-order
    (let ((tail (list 'tail))
          (bag (cl-prolog-kit:fresh-logic-variable "?BAG"))
          (resolved nil))
      (setf (cdr tail) tail)
      (funcall (cl-prolog-kit::%goal-solver 'cl-prolog-kit::findall 4)
               (list 'cl-prolog-kit::findall 'template 'cl-prolog-kit::fail bag tail)
               (make-rulebase) nil nil
               (lambda (environment)
                 (setf resolved (cl-prolog-kit::%walk-term bag environment))))
      (is (eq tail resolved)))))
